# Generated by Django 3.2.5 on 2021-08-02 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundraisingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_id', models.IntegerField()),
                ('plan721_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('threshold_amount', models.IntegerField()),
                ('target_amount', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('fundraising_start_date', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('fundraising_end_date', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('execution_start_date', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('execution_end_date', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('executing_day', models.IntegerField()),
                ('revenue_standard', models.IntegerField()),
                ('profitsharing_investor', models.IntegerField()),
                ('profitsharing_initiator', models.IntegerField()),
                ('profitsharing_platform', models.IntegerField()),
                ('content', models.TextField()),
                ('current_money', models.IntegerField(default=0)),
                ('current_investors', models.IntegerField(default=0)),
                ('product_number', models.IntegerField(default=0)),
                ('image', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='fundraising', max_length=50)),
                ('tx_hash', models.CharField(default='', max_length=255)),
                ('wallet_address', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fund_raising_plan',
            },
        ),
        migrations.CreateModel(
            name='FundraisingProducts',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_id', models.IntegerField()),
                ('plan721_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('plan_id', models.IntegerField()),
            ],
            options={
                'db_table': 'fund_raising_product',
            },
        ),
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('end_date', models.DateTimeField(
                    blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_token', models.IntegerField(default=0)),
                ('blacklist', models.BooleanField(default=False)),
                ('wallet_address', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
