# Generated by Django 3.2.5 on 2021-08-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_test1_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraisingproducts',
            name='plan_id',
        ),
        migrations.AddField(
            model_name='fundraisingproducts',
            name='plan_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fundraisingproducts',
            name='produc_id',
            field=models.IntegerField(default=0),
        ),
    ]
