# Generated by Django 3.2.5 on 2021-08-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210802_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraisingproducts',
            old_name='produc_id',
            new_name='product_id',
        ),
    ]
