# Generated by Django 3.2.5 on 2021-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_produc_id_fundraisingproducts_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_wallet', models.CharField(default='', max_length=255)),
                ('plan_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'investment_record',
            },
        ),
    ]
