# Generated by Django 3.2.5 on 2021-08-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_investmentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrecord',
            name='etherscan_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
