# Generated by Django 3.2.5 on 2021-08-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_fundraisingplan_current_investors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_id', models.IntegerField()),
                ('plan721_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('plan_id', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
                ('issued_amount', models.IntegerField(default=0)),
                ('sold_amount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_wallet', models.CharField(default='', max_length=255)),
                ('plan_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('etherscan_url', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_record',
            },
        ),
        migrations.DeleteModel(
            name='FundraisingProducts',
        ),
    ]
