# Generated by Django 3.2.5 on 2021-08-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210807_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='plan721_id',
        ),
    ]
