# Generated by Django 3.2.5 on 2021-08-10 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_products_plan721_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitSharingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('identity', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.fundraisingplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.products')),
            ],
            options={
                'db_table': 'profit_sharing_record',
            },
        ),
    ]
