# Generated by Django 3.2.5 on 2021-08-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_profitsharingrecord_etherscan_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='etherscan_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='plan721_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
