# Generated by Django 3.2.5 on 2021-08-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20210815_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_1155_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
