# Generated by Django 3.2.5 on 2021-08-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_salesrecord_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
