# Generated by Django 3.2.5 on 2021-08-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_salesrecord_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecord',
            old_name='user_id',
            new_name='buyer_uid',
        ),
        migrations.RenameField(
            model_name='salesrecord',
            old_name='user_wallet',
            new_name='buyer_wallet',
        ),
    ]
