# Generated by Django 3.2.5 on 2021-09-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20210825_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
