# Generated by Django 3.2.5 on 2021-09-12 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_products_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraisingplan',
            name='executing_day',
        ),
        migrations.AddField(
            model_name='fundraisingplan',
            name='liquidation_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fundraisingplan',
            name='liquidation_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='fundraisingplan',
            name='profit_sharing_frequency',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AddField(
            model_name='fundraisingplan',
            name='profit_sharing_start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fundraisingplan',
            name='execution_end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fundraisingplan',
            name='revenue_standard',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
