# Generated by Django 3.2.5 on 2021-10-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20210912_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrecord',
            name='type',
            field=models.CharField(default='invest', max_length=255),
        ),
    ]
