from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('buy-token', views.buy_platform_token, name='buy_platform_token'),
    path('member-info', views.get_member_info, name='get_member_info'),
    path('choose-plan-to-create', views.choose_plan_to_create),
    path('create-plan-for-product', views.create_plan_for_product,
         name='create_plan_for_product'),
    path('create-plan-for-store', views.create_plan_for_store,
         name='create_plan_for_store'),
    path('post-buy-erc865', views.buy_erc865),
    path('get_ecpay_return', views.PaymentReturnView.as_view()),
    path('create-fundraising-product-plan',
         views.post_create_fundraising_product_plan),
    path('create-fundraising-store-plan',
         views.post_create_fundraising_store_plan),
    path('fundraising-plan/<id>', views.get_one_fundraising_plan),
    path('executing-plan/<id>', views.get_one_executing_plan),
    path('closed-plan/<id>', views.get_one_closed_plan),
    path('all-plans/<username>', views.get_initiator_all_plans),
    path('invest-plan/<id>', views.get_invest_plan_page),
    path('invest-plan/<id>/invest-fundraising-products',
         views.post_invest_fundraising_products),
    path('get-plans/<status>', views.get_plans_by_status),
    path('get-transfer-token', views.get_transfer_token),
    path('post-transfer-token', views.post_transfer_token),
    path('record', views.member_history_record),
    path('get-user-investments-by-plan-product-id',
         views.get_user_investments_by_plan_product_id),
    path('close-plan', views.close_plan),
    path('issue-ERC1155-product-api', views.issue_ERC1155_product),
    path('get-remaining-ERC1155-products',
         views.get_remaining_ERC1155_products),
    path('buy-product', views.buy_product),
    path('transfer-invest-token/<plan_id>/<product_id>',
         views.get_transfer_invest_token_page),
    path('transfer-invest-token/<plan_id>/<product_id>/submit',
         views.transfer_invest_token),
    path('burn-invest-token',
         views.get_burn_invest_token),
    path('post-burn-invest-token',
         views.post_burn_invest_token),
    path('test-page', views.show_test_page),
    path('issue-invest-token', views.issue_invest_token),
]
